# Generated by Django 4.2 on 2023-04-26 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegalRexnord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_number',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
